# From the Exec/PMF directory
PRECISION  = DOUBLE
PROFILE    = FALSE
DEBUG      = FALSE
DIM        = 3
COMP       = intel
USE_MPI    = TRUE
USE_OMP    = TRUE
USE_REACT  = TRUE
#HYP_TYPE   = MOL
PELE_HOME  := ../../..
Eos_dir     := Fuego
Reactions_dir := Fuego
Chemistry_Model := grimech30
Transport_dir := EGLib
Bpack   := ./Make.package
Blocs   := .
include ../Make.PeleC
